site_name: Vietnamese customs and traditions
site_url: https://phongtuc.vn
site_description: Vietnamese customs and traditions

repo_url: https://github.com/hautph/phongtuc

theme: minimal-mistakes-jekyll